#ifndef GLOBAL_H
#define GLOBAL_H

#define WALL_SEGMENTS 20
#define ARENA_RADIUS 250

#define MAX_BULLETS 20
#define BULLET_RADIUS 1

#define SHIP_VELOCITY 0.05
#define SHIP_WARNING 20
#define SHIP_COLLISION 1.25

#define SHIP_LENGTH 6
#define SHIP_WIDTH 4
#define SHIP_HEIGHT 2

#define MAX_ASTEROIDS 10
#define ASTEROID_DIVISIONS 25
#define ASTEROID_MIN_SIZE 25
#define ASTEROID_MAX_SIZE 75
#define ASTEROID_MIN_VELOCITY 25
#define ASTEROID_MAX_VELOCITY 75
#define ASTEROID_SPAWN_RADIUS 1.25

#endif // GLOBAL_H